---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp
  template:
    metadata:
      labels:
        app: bggapp
    spec:
      containers:
      - name: bggapp-container
        image: chukmunnlee/bgg-app:nov-2025
        env:
          - name: BGG_DB_USER
            value: root
          - name: BGG_DB_PASSWORD
            value: mydbpassword
          - name: BGG_DB_HOST
            value: bggdb-svc
          - name: BGG_PORT
            value: "5000"
        ports:
          - name: bggapp-port
            containerPort: 5000
        resources:
         requests:
          cpu: 250m
          memory: 128Mi
         limit:
          cpu: 512m
          memory: 256Mi
        readinessProbe:
         exec:
          command:
          - /bin/sh
          - -c 
          - "ls /opt/ready.txt"
        livenessProbe:
         initialDelaySeconds: 15
         periodSeconds: 60
         timeoutSeconds: 5
         httpGet:
          path: /health
          port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
spec:
  selector:
    app: bggapp
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: bggns
spec:
  ingressClassName: nginx
  rules:
    - host: bgg-163.47.9.246.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bggapp-svc
                port:
                  number: 5000
