---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage   # or use your cluster's default storage class

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
  template:
    metadata:
      labels:
        app: bggdb
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: bggdb-pvc
      containers:
        - name: bggdb-container
          image: chukmunnlee/bgg-database:nov-2025
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mydbpassword
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: default
spec:
  type: ClusterIP   # only accessible inside the cluster
  selector:
    app: bggdb
  ports:
    - port: 3306
      targetPort: 3306
