---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp
  template:
    metadata:
      labels:
        app: bggapp
    spec:
      containers:
        - name: bggapp-container
          image: chukmunnlee/bgg-app:nov-2025
          ports:
            - containerPort: 5000
          env:
            - name: BGG_DB_USER
              value: root
            - name: BGG_DB_PASSWORD
              value: mydbpassword
            - name: BGG_DB_HOST
              value: bggdb-svc
            - name: BGG_PORT
              value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: default
spec:
  type: ClusterIP   # internal-only service
  selector:
    app: bggapp
  ports:
    - port: 5000
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: default
spec:
  ingressClassName: nginx   # ensure nginx ingress controller is installed
  rules:
    - host: bgg-163.47.9.246.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bggapp-svc
                port:
                  number: 5000
